services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${WG_CONFIG_DIR:-wgconfig}:/config/wg_confs
    ports:
      - ${WEBUI_PORT:-8080}:${WEBUI_PORT:-8080}
      - ${TORRENTING_PORT:-6881}:${TORRENTING_PORT:-6881}
      - ${TORRENTING_PORT:-6881}:${TORRENTING_PORT:-6881}/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    configs:
      - source: wg0-config
        target: /config/wg_confs/wg0.conf

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:wireguard"
    depends_on:
      - wireguard
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-America/Chicago}
      - WEBUI_PORT=${WEBUI_PORT:-8080}
      - TORRENTING_PORT=${TORRENTING_PORT:-6881}
    volumes:
      - ${DOWNLOADS_DIR:-./qbittorrent/downloads}:/downloads
      - ${CONFIG_DIR:-config}:/config
      - ${INCOMPLETE_DIR:-incomplete}:/incomplete
    restart: unless-stopped

volumes:
  wgconfig:
  config:
  incomplete:

configs:
  wg0-config:
    content: |
      [Interface]
      PrivateKey = ${PRIVATE_KEY}
      Address = ${ADDRESSES}
      DNS = ${DNS:-1.1.1.1,1.0.0.1}

      # Uncomment the next line to set a custom MTU
      # MTU = 1420

      [Peer]
      PublicKey = ${PUBLIC_KEY}
      PresharedKey = ${PRESHARED_KEY}
      Endpoint = ${ENDPOINT}
      AllowedIPs = ${ALLOWED_IPS:-0.0.0.0/0,::/0}
