services:
  ts-stirlingpdf:
    image: tailscale/tailscale:latest
    container_name: ts-stirlingpdf
    network_mode: service:ts-stirlingpdf
    depends_on:
      - ts-stirlingpdf
    restart: unless-stopped
    hostname: ${TS_HOSTNAME}
    environment:
      - TS_AUTHKEY
      - TS_EXTRA_ARGS
      - TS_SERVE_CONFIG=/ts/serve.json
    volumes:
      - tailscale:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    configs:
      - source: ts-config
        target: /ts/serve.json
  stirling-pdf:
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
    volumes:
      - pdf-data:/usr/share/tessdata
      - pdf-data:/configs
      - pdf-data:/customFiles/
      - pdf-data:/logs/
      - pdf-data:/pipeline/
    environment:
      - DISABLE_ADDITIONAL_FEATURES=false
volumes:
  pdf-data:
  tailscale:
configs:
  ts-config:
    content: |
      {
        "TCP": {
          "443": {
            "HTTPS": true
          }
        },
        "Web": {
          "$${TS_CERT_DOMAIN}:443": {
            "Handlers": {
              "/": {
                "Proxy": "http://127.0.0.1:8080"
              }
            }
          }
        },
        "AllowFunnel": {
          "$${TS_CERT_DOMAIN}:443": ${TS_ALLOW_FUNNEL:-false}
        }
      }
