services:
  nextcloud:
    image: ghcr.io/nextcloud-releases/all-in-one:latest
    container_name: nextcloud-aio-mastercontainer # do not change
    init: true
    restart: "unless-stopped"
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # do not change
      - /var/run/docker.sock:/var/run/docker.sock:ro # do not change
    networks:
      - nextcloud_frontend
    ports:
      - 0.0.0.0:8080:8080
    environment:
      APACHE_PORT: 11000
      APACHE_IP_BINDING: 0.0.0.0
      APACHE_ADDITIONAL_NETWORK: nextcloud_frontend
      SKIP_DOMAIN_VALIDATION: true

  ts-nextcloud:
    image: tailscale/tailscale:latest
    container_name: ts-nextcloud
    restart: "unless-stopped"
    hostname: ${TS_HOSTNAME}
    environment:
      - TS_AUTHKEY
      - TS_EXTRA_ARGS
      - TS_SERVE_CONFIG=/ts/serve.json
    volumes:
      - tailscale:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    configs:
      - source: ts-config
        target: /ts/serve.json
    depends_on:
      - nextcloud
    networks:
      - nextcloud_frontend

volumes:
  tailscale:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer

networks:
  nextcloud_frontend:
    name: nextcloud_frontend
    driver: bridge

configs:
  ts-config:
    content: |
      {
        "TCP": {
          "443": {
            "HTTPS": true
          }
        },
        "Web": {
          "$${TS_CERT_DOMAIN}:443": {
            "Handlers": {
              "/": {
                "Proxy": "http://nextcloud-aio-apache:11000"
              }
            }
          }
        },
        "AllowFunnel": {
          "$${TS_CERT_DOMAIN}:443": ${TS_ALLOW_FUNNEL:-false}
        }
      }
