services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: "unless-stopped"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    deploy:
      resources:
        limits:
          memory: 256M
          pids: 50
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:80 || exit 1
      interval: 30s
      retries: 3
    configs:
      - source: caddy-config
        target: /etc/caddy/Caddyfile
    volumes:
      - ${CADDY_SERVE_DIR:-./public}:/srv
    ports:
      - 80:80
    networks:
      - caddy_network

  ts-caddy:
    image: tailscale/tailscale:latest
    container_name: ts-caddy
    restart: "unless-stopped"
    hostname: ${TS_HOSTNAME}
    environment:
      - TS_AUTHKEY
      - TS_EXTRA_ARGS
      - TS_SERVE_CONFIG=/ts/serve.json
    volumes:
      - tailscale:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    configs:
      - source: ts-config
        target: /ts/serve.json
    depends_on:
      - caddy
    networks:
      - caddy_network
volumes:
  tailscale:
networks:
  caddy_network:
    driver: bridge
configs:
  ts-config:
    content: |
      {
        "TCP": {
          "443": {
            "HTTPS": true
          }
        },
        "Web": {
          "$${TS_CERT_DOMAIN}:443": {
            "Handlers": {
              "/": {
                "Proxy": "http://caddy:80"
              }
            }
          }
        },
        "AllowFunnel": {
          "$${TS_CERT_DOMAIN}:443": ${TS_ALLOW_FUNNEL:-false}
        }
      }
  caddy-config:
    content: |
      :80 {
        root * /srv
        basic_auth {
          ${CADDY_AUTH_USER} ${CADDY_AUTH_HASH}
        }
        file_server browse
        log {
          output stdout
          format console
        }
      }
